/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aakobaissi.gui;

/**
 *
 * @author Abdullah K
 */
public class FastWithdrawScreen extends javax.swing.JFrame {

    /**
     * Creates new form WithdrawScreen
     */
    public FastWithdrawScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fastWithdrawLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        twentyButton = new javax.swing.JButton();
        fortyButton = new javax.swing.JButton();
        sixtyButton = new javax.swing.JButton();
        eightyButton = new javax.swing.JButton();
        hundredButton = new javax.swing.JButton();
        otherAmountButton = new javax.swing.JButton();
        backToMenuButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fastWithdrawLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        fastWithdrawLabel.setText("FAST WITHDRAW");

        twentyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        twentyButton.setText("$20");
        twentyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyButtonActionPerformed(evt);
            }
        });

        fortyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fortyButton.setText("$40");
        fortyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fortyButtonActionPerformed(evt);
            }
        });

        sixtyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sixtyButton.setText("$60");
        sixtyButton.setActionCommand("$60");
        sixtyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixtyButtonActionPerformed(evt);
            }
        });

        eightyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eightyButton.setText("$80");
        eightyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightyButtonActionPerformed(evt);
            }
        });

        hundredButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hundredButton.setText("$100");
        hundredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hundredButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(twentyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(fortyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(sixtyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(eightyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(hundredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twentyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fortyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixtyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eightyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hundredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        otherAmountButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        otherAmountButton.setText("Other Amount");
        otherAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherAmountButtonActionPerformed(evt);
            }
        });

        backToMenuButton2.setText("main menu");
        backToMenuButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fastWithdrawLabel)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(otherAmountButton)
                        .addGap(204, 204, 204)
                        .addComponent(backToMenuButton2)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fastWithdrawLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(otherAmountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backToMenuButton2)
                        .addGap(19, 19, 19))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void twentyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyButtonActionPerformed
        // TODO add your handling code here:
        //fast withdraw $20 will complete the transaction immediately with one click and subtract bill amount from ATM and dollar amount from account balance (once database is fully implemented)
    }//GEN-LAST:event_twentyButtonActionPerformed

    private void fortyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fortyButtonActionPerformed
        // TODO add your handling code here:
        //fast withdraw $40 will complete the transaction immediately with one click and subtract bill amount from ATM and dollar amount from account balance (once database is fully implemented)
    }//GEN-LAST:event_fortyButtonActionPerformed

    private void sixtyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixtyButtonActionPerformed
        // TODO add your handling code here:
        //fast withdraw $60 will complete the transaction immediately with one click and subtract bill amount from ATM and dollar amount from account balance (once database is fully implemented)
    }//GEN-LAST:event_sixtyButtonActionPerformed

    private void eightyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightyButtonActionPerformed
        // TODO add your handling code here:
        //fast withdraw $80 will complete the transaction immediately with one click and subtract bill amount from ATM and dollar amount from account balance (once database is fully implemented)
    }//GEN-LAST:event_eightyButtonActionPerformed

    private void hundredButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hundredButtonActionPerformed
        // TODO add your handling code here:
        //fast withdraw $100 will complete the transaction immediately with one click and subtract bill amount from ATM and dollar amount from account balance (once database is fully implemented)
    }//GEN-LAST:event_hundredButtonActionPerformed

    private void backToMenuButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButton2ActionPerformed
        // TODO add your handling code here:
        new MenuScreen().setVisible(true);  //will return to the main menu and dispose of current screen
        dispose();
    }//GEN-LAST:event_backToMenuButton2ActionPerformed

    //if customer wants to withdraw custom amount
    private void otherAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherAmountButtonActionPerformed
        // TODO add your handling code here:
        new CustomWithdrawalScreen().setVisible(true);  //will open custom withdraw screen and dispose of current screen
        dispose();
    }//GEN-LAST:event_otherAmountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastWithdrawScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastWithdrawScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastWithdrawScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastWithdrawScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastWithdrawScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuButton2;
    private javax.swing.JButton eightyButton;
    private javax.swing.JLabel fastWithdrawLabel;
    private javax.swing.JButton fortyButton;
    private javax.swing.JButton hundredButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton otherAmountButton;
    private javax.swing.JButton sixtyButton;
    private javax.swing.JButton twentyButton;
    // End of variables declaration//GEN-END:variables
}
